### ISSUE TITLE
Assembled boards

### ISSUE THREAD

**Issue by rabarar** [revk/ESP32-PN532#2]
Revk do you sell an assembled board? I want to do some experiments to start and cook want to green up board fan for unit one.

**Comment by revk** [comment]
I am thinking of doing so - chip supply is an issue, and we have been working out if they can be sold as "parts" without CE/UKCA marking, which we think they may be. But no idea when.

**Comment by rabarar** [comment]
Thanks! I’ll watch the repo for an update if/when you decide you can — thanks again!
