### ISSUE TITLE
The project symbol library cache file 'PN532-cache.lib' was not found.

### ISSUE THREAD

**Issue by hillstub** [revk/ESP32-PN532#3]
Hi revk,
Thanks for your awesome work!! 

I'm working on making an ESP32-based board (ESP32-H2 once it's available) with NFC. Currently, I'm trying to get some inspiration from your project ;-).

Unfortunately, when I open the KiCad schematic file, I'm getting the following error: "The project symbol library cache file 'PN532-cache.lib' was not found." Am I doing something wrong or is it looking for a file that's not in the repo?

Thanks again!

**Comment by revk** [comment]
OK not sure, I am just updating stuff to kicad 6 now though.

**Comment by revk** [comment]
I have updated the files for KiCad 6 - hope that helps.

**Comment by hillstub** [comment]
Yes! That resolved the issue - tnx!!
