### ISSUE TITLE
Interesting project.

### ISSUE THREAD

**Issue by RaveGun** [revk/ESP32-PN532#5]
Nice project.

I did some, too much, time ago for the office where I work, a NFC reader to count the number of coffees each one is drinking. We all have some NFC access IDs with unique ID number. The device is made out of the Wemos D1 Mini, a SD card adapter, an OLED display, a PN532 dev-board (the bigger blue one) and a custom board to glue everything together. It is all in my GitHub.

Now that our team has expanded was needed to build another one and it was so hard to find similar parts that are working like the old one. The software is also old and I just found the binary from back then and programmed the new board. After a lot of stress and debugging I managed to make a new device. This made me thinking I should try to build a new version with newer components.

**Do you think that the PN532 is still the way to go for a NFC reader?**
I need to mention that the IDs are of some Desfire type so I guess are more special then the regular NFC coins and need some features. The usual MFRC522 is not good enough. 

I think that the ESP + NFC chip + SD card shall be integrated on one board. 
The device I am thinking of does not have to be too small, it shall accommodate for an off the shelf >2.5" display.

**Can the NFC antenna be bigger than a credit card?**
For me antennas are some sort of voodoo magic.

**Comment by revk** [comment]
The PN532 works with DESFire, that is what we are using it for.

I have generally kept the NFC on a separate board. I suspect it could be done on one board with care.

Antennas are voodoo, and this one works. Why do you need bigger than a credit card. It works well with the credit card size devices, from several cm away in fact.

**Comment by RaveGun** [comment]
It looks like the PN532 is EOL and there are other recommended ICs now, this is why I was asking.

I was thinking that, if it is bigger I will be easier to integrate all in one PCB and save on the board to board connections.
Also, to do it on one side and then just order the PCBs with assembly. I don't know, I am just thinking(writing) out loud :)
I am an embedded SW guy and know about HW and HW design just enough to be able to find where the micro-controller's pins are going :)

Thank you for your time.

**Comment by revk** [comment]
Yeh, I have not yet looked at alternative chips. Need to work out how much the interface changes as well. And designing an RF board is always, err, fun... So I may well make a new design soon. But PN532 work well for now.

**Comment by revk** [comment]
Also, the PN7150 does not have HSU or GPIO. For my applications the reader is on a short lead which is far better done as HSU where the pins are driven all the time, than I2C, and I use the GPIO for LEDs. Would be interesting to find a newer chip that does HSU and GPIO like the PN532. Suggestions welcome.

**Comment by RaveGun** [comment]
It looks like the PN5331B3HN is the next one in the list, that is still active and matches your requirements. It has no SPI nor I2C but it has USB2.0 as an interface. This is interesting as there are now also boards in internet that have the PN532 and an USB interface (something with GRID v2).
